project:
  title: "covid-19-vaccination-ch-qmd"
  render:
    - covid-19-vaccination-ch-qmd.qmd
    - Tests.qmd
    - Presentation.qmd
    - shinyexample.qmd

editor: visual

execute:
  echo: false
  warning: false
  
colorlinks: true

