---
title: "Migration notes"
---

## R Packages

With latest version of knitr and all packages we observed a problem with rendering plotly graphs.

The 'yaml' package is required to parse dependencies within Quarto Markdown files. To be added to the renv project

## renv

Source:

https://community.rstudio.com/t/possibility-to-specify-renv-for-quarto-render/161423

renv can be added, the DESCRIPTION file can be first be in the project to allow renv::restore()

We could use the same set up as for the old app:

R. 4.2.1 Same renv.lock file.

## Shiny

The Quarto website is ultimately a static website - it won't be responding to user input or running any R code. You can embed a shiny app into a qmd that you render in the rstudio IDE and it'll work just fine because the shiny app is running in a session on your computer. Website hosting services like quarto-pub, netlify, and gh-pages will only be serving up the html pages of the site, not running the code necessary to operate the shiny app in response to user input.

https://github.com/quarto-dev/quarto-cli/discussions/1561

Shiny #\| context: server does not pick the objects run the R chunks,

Trick: save them as rds in the project, read them Not a big speed issue, given that shinyapps.io will load the html file

## Shinyapps.io

The Qmd file cannot be in the INST folder, when deploying to Shinyapps.io Sourcing R folders does not work.

## Good sources

-   [R Quarto Tutorial -- How To Create Interactive Markdown Documents](https://r-craft.org/r-news/r-quarto-tutorial-how-to-create-interactive-markdown-documents/)

-   [htmlwidgets for R](https://quarto.org/docs/interactive/widgets/htmlwidgets.html)

-   [Use Shiny with Quarto](https://quarto.org/docs/interactive/shiny/)

-   [Interactive Quarto Reports with Shiny using {shiny.i18n}](https://www.r-bloggers.com/2023/03/interactive-quarto-reports-with-shiny-using-shiny-i18n/)

https://quarto.org/docs/blog/posts/2022-10-25-shinylive-extension/

-   [ShinyApp Quarto blog](https://community.rstudio.com/t/shinyapp-in-quarto-blog/159319/2)

https://jauntyjjs.github.io/Trelliscopejs_In_Quarto_Example/

I'm an R user: Quarto or R Markdown?

https://www.jumpingrivers.com/blog/quarto-rmarkdown-comparison/

[Notes on Changing from Rmarkdown/Bookdown to Quarto](https://www.njtierney.com/post/2022/04/11/rmd-to-qmd/)

[FAQ for R Markdown users](https://quarto.org/docs/faq/rmarkdown.html)

https://laderast.github.io/qmd_rmd/#/what-is-quarto-1

## Videos

Why moving to Quarto https://www.youtube.com/watch?v=mGNW8jl7RMc

1.  Quarto offers many out of the box features, Rmarkdown must use extension packages

2.  Quarto is multi-language and multi engine, other languages can be used.

3.  Easy migration, easy compatibility with Markdown and Jupyther

<!-- 4. On Shinyapps.io quarto renders the html file in the project, Rmarkdown renders the Rmd file and executes all the code, which makes it much faster to load in Quarto -->

<!-- See log file Rmarkdown -->

<!-- https://www.shinyapps.io/admin/#/application/5623831/logs -->

<!-- See logfile Quarto -->

<!-- https://www.shinyapps.io/admin/#/application/9456928/logs -->

## 1.

Features:

Markdown: bookdown, blogdown, distill (science publish), xaringan (presentation)

Quarto offers all, it contr no need to depend on these external packgaes

## 1.
